import Head from "next/head";
import Agenda from "./components/Agenda";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center h-screen bg-slate-100 font-domine">
        <Agenda />
      </main>
    </div>
  );
}
