import Head from "next/head";
import { useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { Suspense } from "react";
import Scene from "./components/Scene";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Clock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen bg-slate-200">
        <Suspense fallback="Ik heb een zwaar leven">
          <Canvas shadows flat linear>
            <Scene className="min-h-screen" />
          </Canvas>
        </Suspense>
      </main>
    </div>
  );
}
