import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { Suspense } from "react";
import Scene from "./components/Scene";
import { useState, useEffect } from "react";
import { OrbitControls } from "@react-three/drei";
import SceneLarge from "./components/SceneLarge";

export default function Home() {
  const [date, setDate] = useState(new Date());

  useEffect(() => {
    const timer = setInterval(() => setDate(new Date()), 1000);

    return () => {
      clearInterval(timer);
    };
  });

  const secondsDegree = (date.getSeconds() / 60) * 360;
  const minutesDegree = (date.getMinutes() / 60) * 360;
  const hoursDegree = (date.getHours() / 12) * 360;

  return (
    <div>
      <Head>
        <title>Clock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen bg-slate-200">
        <Suspense fallback="Ik heb een zwaar leven">
          <Canvas shadows flat linear>
            <SceneLarge
              className="min-h-screen"
              secondsDegree={secondsDegree}
              minutesDegree={minutesDegree}
              hoursDegree={hoursDegree}
            />
            <OrbitControls />
          </Canvas>
        </Suspense>
      </main>
    </div>
  );
}
