/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({
  secondsDegree,
  minutesDegree,
  hoursDegree,
  ...props
}) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/JLDFiPmqR39QQjGz/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#f5eee4"]} />
      <group {...props} dispose={null}>
        <OrthographicCamera
          name="Camera"
          makeDefault={true}
          far={100000}
          near={-100000}
          up={[0, 1, 0]}
          position={[216, 39, 1000]}
          rotation={[0, 0, 0]}
        />
        <directionalLight
          name="Directional Light 2"
          castShadow
          intensity={0.95}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-2350.233}
          shadow-camera-right={2350.233}
          shadow-camera-top={2350.233}
          shadow-camera-bottom={-2350.233}
          color="#a1a1a1"
          position={[-603.34, 711.69, -208.15]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.69}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1655.8065}
          shadow-camera-right={1655.8065}
          shadow-camera-top={1655.8065}
          shadow-camera-bottom={-1655.8065}
          position={[200, 300, 300]}
        />
        <group
          name="Book"
          position={[370.64, 110.11, 38.65]}
          rotation={[-0.11, 0, 0]}
          scale={1.4}
        >
          <mesh
            name="Cube 2"
            geometry={nodes["Cube 2"].geometry}
            material={nodes["Cube 2"].material}
            castShadow
            receiveShadow
            position={[371.03, 108.03, 40.64]}
            rotation={[3.03, 0, -Math.PI]}
            scale={1.4}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            castShadow
            receiveShadow
            position={[371.03, 109.88, 38.84]}
            rotation={[3.03, 0, -Math.PI]}
            scale={1.4}
          />
          <mesh
            name="Cover 3"
            geometry={nodes["Cover 3"].geometry}
            material={nodes["Cover 3"].material}
            castShadow
            receiveShadow
            position={[370.63, 103.38, -23.59]}
            rotation={[3.03, 0, -Math.PI]}
            scale={1.4}
          />
        </group>
        <mesh
          name="Glass"
          geometry={nodes.Glass.geometry}
          material={nodes.Glass.material}
          castShadow
          receiveShadow
          position={[-540.38, 0, 165.02]}
          rotation={[Math.PI / 2, 0, 0]}
        />

        <group
          name="Wijzer - groot"
          position={[-539.38, 1.39, 170.95]}
          rotation={[0, 0, 100]}
        >
          <mesh
            name="Wijzer wit"
            geometry={nodes["Wijzer wit"].geometry}
            material={materials["Wijzer wit Material"]}
            castShadow
            receiveShadow
            position={[0, 99.2, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            name="Wijzer zwart"
            geometry={nodes["Wijzer zwart"].geometry}
            material={materials["Wijzer zwart"]}
            castShadow
            receiveShadow
            position={[0, 67.84, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group
          name="Wijzer -klein"
          position={[-539.38, 1, 174.17]}
          rotation={[0, 0, hoursDegree]}
        >
          <mesh
            name="Wijzer wit1"
            geometry={nodes["Wijzer wit1"].geometry}
            material={materials["Wijzer wit1 Material"]}
            castShadow
            receiveShadow
            position={[0, 66.92, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
          <mesh
            name="Wijzer zwart1"
            geometry={nodes["Wijzer zwart1"].geometry}
            material={materials["Wijzer zwart"]}
            castShadow
            receiveShadow
            position={[0, 44.24, 0]}
            rotation={[0, 0, Math.PI / 2]}
          />
        </group>
        <group
          name="Secondenwijzer"
          position={[-539.38, 0.54, 166.34]}
          rotation={[0, 0, secondsDegree]}
        >
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials["Ellipse Material"]}
            castShadow
            receiveShadow
            position={[0, 1.15, 0]}
            rotation={[0, 0, 1.61]}
            scale={1}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials["Rectangle Material"]}
            castShadow
            receiveShadow
            position={[0, 55.68, 0]}
            rotation={[0, 0, 1.61]}
            scale={[1, 1, 11.55]}
          />
        </group>
        <group name="Wijzers dekplaat" position={[-539.38, 1, 175.58]}>
          <mesh
            name="Ellipse 2"
            geometry={nodes["Ellipse 2"].geometry}
            material={materials["Ellipse 2 Material"]}
            castShadow
            receiveShadow
            position={[0, 1, 0]}
          />
          <mesh
            name="Ellipse1"
            geometry={nodes.Ellipse1.geometry}
            material={materials["Wijzer zwart"]}
            castShadow
            receiveShadow
            position={[0, 1, 0]}
          />
        </group>
        <mesh
          name="Knop"
          geometry={nodes.Knop.geometry}
          material={nodes.Knop.material}
          castShadow
          receiveShadow
          position={[-538.38, 231.61, 85.88]}
        />
        <mesh
          name="Ellipse2"
          geometry={nodes.Ellipse2.geometry}
          material={materials["Ellipse2 Material"]}
          castShadow
          receiveShadow
          position={[-538.38, 1, 158.85]}
        />
        <mesh
          name="Case white"
          geometry={nodes["Case white"].geometry}
          material={nodes["Case white"].material}
          castShadow
          receiveShadow
          position={[-538.38, 1, 10.84]}
        />
        <mesh
          name="Case orange"
          geometry={nodes["Case orange"].geometry}
          material={nodes["Case orange"].material}
          castShadow
          receiveShadow
          position={[-538.38, 1, 4.95]}
        />
        <mesh
          name="Vloersteun"
          geometry={nodes.Vloersteun.geometry}
          material={materials["Orange case"]}
          castShadow
          receiveShadow
          position={[-539.38, -195.45, 21.22]}
        />
        <group name="Achtergrond" position={[-305.41, 0, -300.99]}>
          <mesh
            name="Cube 4"
            geometry={nodes["Cube 4"].geometry}
            material={materials["Cube 4 Material"]}
            castShadow
            receiveShadow
            position={[-284.91, 274.69, -992.45]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Cube 3"
            geometry={nodes["Cube 3"].geometry}
            material={materials["Cube 3 Material"]}
            castShadow
            receiveShadow
            position={[-319.65, -517.2, -300.99]}
          />
        </group>
        <hemisphereLight
          name="Default Ambient Light"
          intensity={1.32}
          color="#b49e85"
        />
      </group>
    </>
  );
}
